In [1]:
import pandas as pd

In [3]:
import pandas as pd

transacciones = pd.DataFrame({
"id_producto": [101, 102, 103, 101, 104],
"cantidad": [2, 1, 5, 3, None],
"fecha": [
"2025-01-10",
"2025-01-11",
"2025-01-12",
"2025-01-13",
"2025-01-14"
]
})

transacciones

   id_producto  cantidad       fecha
0          101       2.0  2025-01-10
1          102       1.0  2025-01-11
2          103       5.0  2025-01-12
3          101       3.0  2025-01-13
4          104       NaN  2025-01-14

In [4]:
transacciones.to_csv(
"transacciones.csv",
index=False
)

In [5]:
productos = pd.DataFrame({
"id_producto": [101, 102, 103, 104],
"nombre_producto": [
"Teclado",
"Ratón",
"Monitor",
"Auriculares"
],
"precio_unitario": [
25.50,
15.00,
180.00,
40.00
]
})

productos

   id_producto nombre_producto  precio_unitario
0          101         Teclado             25.5
1          102           Ratón             15.0
2          103         Monitor            180.0
3          104     Auriculares             40.0

In [6]:
productos.to_excel(
"productos.xlsx",
index=False
)

In [7]:
import os

os.listdir()

['.config', 'productos.xlsx', 'transacciones.csv', 'sample_data']

In [8]:
transacciones = pd.read_csv("transacciones.csv")

productos = pd.read_excel(
"productos.xlsx",
engine="openpyxl"
)

print(transacciones.head())
print()
print(productos.head())

   id_producto  cantidad       fecha
0          101       2.0  2025-01-10
1          102       1.0  2025-01-11
2          103       5.0  2025-01-12
3          101       3.0  2025-01-13
4          104       NaN  2025-01-14

   id_producto nombre_producto  precio_unitario
0          101         Teclado             25.5
1          102           Ratón             15.0
2          103         Monitor            180.0
3          104     Auriculares             40.0

In [9]:
print(transacciones.dtypes)
print()
print(productos.dtypes)

id_producto      int64
cantidad       float64
fecha           object
dtype: object

id_producto          int64
nombre_producto     object
precio_unitario    float64
dtype: object

In [12]:
transacciones["fecha"] = pd.to_datetime(
transacciones["fecha"]
)

print(transacciones.dtypes)

id_producto             int64
cantidad              float64
fecha          datetime64[ns]
dtype: object

In [13]:
print(transacciones.isnull().sum())

id_producto    0
cantidad       1
fecha          0
dtype: int64

In [14]:
transacciones["cantidad"] = (
transacciones["cantidad"].fillna(0)
)

In [15]:
print(transacciones.isnull().sum())

id_producto    0
cantidad       0
fecha          0
dtype: int64

In [16]:
ventas = pd.merge(
transacciones,
productos,
on="id_producto",
how="left"
)
ventas

   id_producto  cantidad      fecha nombre_producto  precio_unitario
0          101       2.0 2025-01-10         Teclado             25.5
1          102       1.0 2025-01-11           Ratón             15.0
2          103       5.0 2025-01-12         Monitor            180.0
3          101       3.0 2025-01-13         Teclado             25.5
4          104       0.0 2025-01-14     Auriculares             40.0

In [17]:
ventas["total_venta"] = (
ventas["cantidad"] *
ventas["precio_unitario"]
)
ventas

,id_producto,cantidad,fecha,nombre_producto,precio_unitario,total_venta
0,101,2.0,2025-01-10,Teclado,25.5,51.0
1,102,1.0,2025-01-11,Ratón,15.0,15.0
2,103,5.0,2025-01-12,Monitor,180.0,900.0
3,101,3.0,2025-01-13,Teclado,25.5,76.5
4,104,0.0,2025-01-14,Auriculares,40.0,0.0

In [18]:
print(ventas.isnull().sum())

id_producto        0
cantidad           0
fecha              0
nombre_producto    0
precio_unitario    0
total_venta        0
dtype: int64

In [19]:
ventas.to_parquet(
"ventas_normalizadas.parquet",
index=False
)

In [20]:
import os

os.listdir()

['.config',
 'ventas_normalizadas.parquet',
 'productos.xlsx',
 'transacciones.csv',
 'sample_data']